### ISSUE TITLE
Issues that need to be triaged after walking Sitemap

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#27]
## Trailing dots on section identifiers
**resolution:** Moved these into potential patches for OFR to review, in the interim the plan is to update versioner to strip trailing dots from identifiers.
https://github.com/criticaljuncture/ecfr-xml-corrections/issues/33
- [x] extra dot
https://ecfr.criticaljuncture.org/current/title-39/chapter-I/subchapter-A/part-3/section-3.10.
- [x] extra dot
https://ecfr.criticaljuncture.org/current/title-38/chapter-I/part-38/section-38.628.
- [x] See if Title 20 - Part 350 has a fat-fingered dot on 350.6
https://ecfr.criticaljuncture.org/current/title-20/chapter-II/subchapter-D/part-350/section-350.6.
- [x] Looks like this has an extra dot
https://ecfr.criticaljuncture.org/current/title-32/subtitle-A/chapter-I/subchapter-M/part-239/section-239.15.
- [x] Looks like this has an extra dot
https://ecfr.criticaljuncture.org/current/title-32/subtitle-B/chapter-XIX/part-1907/section-1907.24."

## Other errors
- [x] 500ing, maybe bad content?
{"status"=>500, "url"=>"https://ecfr.criticaljuncture.org/current/title-34/subtitle-B/chapter-VI/part-668/subpart-G/section-668.90"}
{"status"=>500, "url"=>"https://ecfr.criticaljuncture.org/current/title-34/subtitle-B/chapter-VI/part-668/subpart-G/section-668.93"}

**resolution:** This is an issue with FrCrossReferences having nil effective_on dates. Created issue:
https://github.com/criticaljuncture/ecfr-web/issues/253

- [x] See why this part has no identifier
https://ecfr.criticaljuncture.org/current/title-24/subtitle-A/part-/appendix-Appendixes%20A-C%20to%20%20A%20%5BReserved%5D
**outcome: There is a part with no identifier that wraps this appendix, but this is a reserved appendix that we don't link to anyway.**

- [x] Problem with cross references documents
https://app.honeybadger.io/projects/51157/faults/37488761#notice-summary
**resolution:** This is an issue with FrCrossReferences having nil effective_on dates. Created issue:
https://github.com/criticaljuncture/ecfr-web/issues/253

- [x] undefined method text for nil
Title 22 Part 709 subchapter A
https://app.honeybadger.io/projects/51157/faults/35570252#notice-summary
**TODO Talk to Bob about this and figure out whats missing**

** Created renderer ticket for Bob:**
https://github.com/criticaljuncture/ecfr-renderer/issues/13

```ruby
# ecfr-renderer
# /lib/xslt_functions.rb:23
if section.present?
  footnote = section.xpath('.//FTNT//P').select do |footnote_node|
    footnote_node.xpath('.//SU').first.text == footref
  end.first
else
```
xml:
```xml
<DIV8 N="§ 709.1" TYPE="SECTION">
<HEAD>§ 709.1   Authority and purpose.</HEAD>

<P>
	(a) These regulations are issued under the general powers of the Overseas Private Investment Corporation (“OPIC”) and pursuant to section 237(1) of the Foreign Assistance Act of 1961, added by Pub. L. 95-268. 
	<SU>1</SU>
	<FTREF/> The Board of Directors of OPIC has authorized the President of OPIC to issue these regulations and to amend them as the President shall deem appropriate.
</P>

<FTNT>

<P>
	<SU>1</SU> Section 237(1) of that Act states:
</P>

<P>(1) No payment may be made under any insurance or reinsurance which is issued under this title on or after the date of enactment of this subsection for any loss occurring with respect to a project, if the preponderant cause of such loss was an act by the investor seeking payment under this title, by a person possessing majority ownership and control of the investor at the time of the act, or by any agent of such investor or controlling person, and a court of the United States has entered a final judgment that such act constituted a violation under the Foreign Corrupt Practices Act of 1977.
</P>

<P>(2) Not later than 120 days after the date of enactment of this subsection, the Corporation shall adopt regulations setting forth appropriate conditions under which any person convicted under the Foreign Corrupt Practices Act of 1977 for an offense related to a project insured or otherwise supported by the Corporation shall be suspended, for a period of not more than 5 years, from eligibility to receive any insurance, reinsurance, guaranty, loan or other financial support authorized by this title.</P>
</FTNT>

<P>(b) These regulations prescribe the procedure under which individuals and companies may be suspended, as mandated by section 237(1) of the Foreign Assistance Act of 1961, as amended, from eligibility for OPIC services because of conviction under the Foreign Corrupt Practices Act of 1977 (Pub. L. 95-213) of an offense related to an OPIC-supported project.
</P>

<P>(c) The purposes of the suspensions provided herein are to carry out the statutory requirements of Section 237(1) of the Foreign Assistance Act of 1961, as amended, to protect the interest of the United States and to foster full and free competition in international commerce.
</P>

<P>(d) The specific provisions of law under which OPIC operates and the general powers conferred on OPIC give OPIC broad discretion in the conduct of its programs. The issuance of these regulations is not to be construed as in any way limiting or derogating from the discretion of OPIC to determine whether or not to support the investment of a particular entity in a particular case.
</P>
</DIV8>
```

**Comment by barefootford** [comment]
These are all triaged and/or pulled into other, new linked tickets
