### ISSUE TITLE
Data items to review with OFR

### ISSUE THREAD

**Issue by peregrinator** [criticaljuncture/ecfr-xml-corrections#56]
This is a wrapper around other tickets that we either need decisions from OFR on or that we've patched but would like them to fix in the SGML/XML

## XML Patches
- [x] Remove duplicate section  `48 CFR 852.232-70` (Removed with a patch) https://github.com/criticaljuncture/ecfr-xml-corrections/issues/52

#### Need discussion
- [x] Title 33 has amendment date with two dates (`<AMDDATE>Dec. 24, 26, 2018</AMDDATE>`) https://github.com/criticaljuncture/ecfr-xml-corrections/issues/72
- [x] `7 CFR 1773` has all subparts duplicated in current xml https://github.com/criticaljuncture/ecfr-xml-corrections/issues/51
- [x] `47 CFR 400` has 10 duplicate sections in current xml https://github.com/criticaljuncture/ecfr-xml-corrections/issues/50
- [x] Patch Title 5 Ammdate 20199 https://github.com/criticaljuncture/ecfr-xml-corrections/issues/73

## eCFR Corrections
- [x] Fix Typo in eCFR Correction - 7 CFR 301-38-2 https://github.com/criticaljuncture/ecfr-web/issues/363
- [x] Should we remove duplicate correction `38 CFR 4.118` table corrected https://github.com/criticaljuncture/ecfr-versioner/issues/192
- [x] `41 CFR 109-26, 41 CFR 109-40` error corrected day is listed as a day before they were actually corrected in XML. Is this common or a one-off? https://github.com/criticaljuncture/ecfr-versioner/issues/87

## Functionality/Appearance (Need further discussion)
- [x] Can we remove pseudo TOC inserted as part node in `40 CFR Chapter V` https://github.com/criticaljuncture/ecfr-versioner/issues/114
- [x] Could we update link service to support volumes? https://github.com/criticaljuncture/ecfr-web/issues/303
- [x] How to handle multiple nullified sections in Title 30 https://github.com/criticaljuncture/ecfr-xml-corrections/issues/49
- [x] 49 CFR 192.175 has a change on 2018-06-20, but no FR doc or eCFR (change log) includes a notice on these changes https://github.com/criticaljuncture/ecfr-xml-corrections/issues/54
- [x] Can we patch 15 CFR 2004 part without identifier when it is later updated to include identifier and child sections include identifier? https://github.com/criticaljuncture/ecfr-xml-corrections/issues/54
